site_name: pktvisor edge observability agent
theme:
  name: material
  favicon: img/ORB-logo-ring.png
  logo: img/ORB-logo-ring.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - abbr
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
plugins:
  - search
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Installation: 'install.md'
  - Documentation: 'docs.md'
  - Community: 'contact.md'
repo_url: https://github.com/ns1labs/pktvisor
edit_uri: edit/main/docs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ns1labs/pktvisor
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ns1labs/pktvisor
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/ns1labs/shared_invite/zt-p0uzy9zq-ZgD~QkKQ9cWMSiI4DgJSaA
    - icon: octicons/mail-24
      link: "mailto:info@pktvisor.dev"
google_analytics:
  - UA-41778111-8
  - auto
copyright: Copyright &copy; 2022 <a href="https://ns1.com/labs">NS1</a>
